### PR TITLE
feat: Add a shortcut keybinding

### PR DESCRIPTION
**Pull request by chenweiyi**
### Description
Add a shortcut keybinding (default Ctrl+Shift+W) to open the "quickSwitchWindow" selection list for clicking the status bar, and also add a command to open the "quickSwitchWindow" selection list.

### CODE REVIEW

**Comment by zcf0508** [comment]
Nice work! 🫵

**Comment by antfu** [comment]
Why not just bind to `workbench.action.quickSwitchWindow` directly? Also you can use Ctrl+R (on mac) to select the recent projects.

**Comment by chenweiyi** [comment]
> Why not just bind to `workbench.action.quickSwitchWindow` directly? Also you can use Ctrl+R (on mac) to select the recent projects.

Yeah, seems ctrl + R works fine. 
I can rewrite the code, bing to workbrench.action.quickSwitchWindow directly. If I modify the code, can you merge my pr?😊
I like the status bar and this let me know where I am working in.

**Comment by antfu** [comment]
To bind the command I think you don't need to write any code, it's directly do able in VS Code UI. Thanks.

**Comment by zcf0508** [comment]
Perhaps it would be a good idea to display a list of custom project names by pressing a hotkey?

**Pull request closed without merging**
